name: intl_phone_number_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.7.1
homepage: https://github.com/natintosh/intl-phone-number-input
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  libphonenumber_plugin: 0.2.3
  equatable: 2.0.3
  collection: 1.17.1
  # flutter_neumorphic: 3.2.0
  mobile_dependencies:
    git:
      url: https://human-forest:Nytt1ycZ7CppE1jX_eUB@gitlab.com/human-forest/human-forest-mobile-app/mobile_dependencies.git
      ref: feature/flutter_3-10

dependency_overrides:
  mobile_dependencies:
    path: /Users/favaz-human-forest/Desktop/HumanForestApp/mobile_dependencies
  mobile_design_system:
    path: /Users/favaz-human-forest/Desktop/HumanForestApp/mobile_design_system

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/flags/
